CREATE TABLE `mqtt_emqx` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `event` varchar(50) DEFAULT NULL,
  `clientid` varchar(50) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `node` varchar(50) DEFAULT NULL,
  `timestamp` bigint DEFAULT NULL,
  `peername` varchar(50) DEFAULT NULL,
  `sockname` varchar(50) DEFAULT NULL,
  `proto_name` varchar(20) DEFAULT NULL,
  `proto_ver` float DEFAULT NULL,
  `peerhost` varchar(50) DEFAULT NULL,
  `topic` varchar(100) DEFAULT NULL,
  `qos` tinyint(1) DEFAULT 0,
  `payload` varchar(1000) DEFAULT NULL,
  `mid` varchar(50) DEFAULT NULL,
  `publish_received_at` bigint DEFAULT NULL,
  `from_username` varchar(50) DEFAULT NULL,
  `from_clientid` varchar(50) DEFAULT NULL,
  `disconnected_at` bigint DEFAULT NULL,
  `reason` varchar(50) DEFAULT NULL,
  `user_properties` varchar(500) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
